# OpenAPI Contract: Todo API Backend

openapi: 3.0.0
info:
  title: Todo API Backend
  version: 1.0.0
  description: Phase II Todo API Backend for Evolution of Todo project

paths:
  /api/{user_id}/tasks:
    get:
      summary: List all tasks for a user
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of tasks for the user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '500':
          description: Internal server error
    post:
      summary: Create a new task for a user
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid request data
        '500':
          description: Internal server error

  /api/{user_id}/tasks/{id}:
    get:
      summary: Get a specific task
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
        '500':
          description: Internal server error
    put:
      summary: Update a specific task
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
        '400':
          description: Invalid request data
        '500':
          description: Internal server error
    delete:
      summary: Delete a specific task
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Task deleted successfully
        '404':
          description: Task not found
        '500':
          description: Internal server error

  /api/{user_id}/tasks/{id}/complete:
    patch:
      summary: Toggle task completion status
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task completion status updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
        '500':
          description: Internal server error

components:
  schemas:
    TaskBase:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          description: Title of the task
        description:
          type: string
          description: Optional description of the task
        completed:
          type: boolean
          description: Whether the task is completed
          default: false
    TaskCreate:
      allOf:
        - $ref: '#/components/schemas/TaskBase'
    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          description: Title of the task (optional for updates)
        description:
          type: string
          description: Optional description of the task (optional for updates)
        completed:
          type: boolean
          description: Whether the task is completed (optional for updates)
    Task:
      allOf:
        - $ref: '#/components/schemas/TaskBase'
        - type: object
          required:
            - id
            - user_id
            - created_at
            - updated_at
          properties:
            id:
              type: string
              description: Unique identifier for the task
            user_id:
              type: string
              description: ID of the user who owns this task
            created_at:
              type: string
              format: date-time
              description: Timestamp when the task was created
            updated_at:
              type: string
              format: date-time
              description: Timestamp when the task was last updated